services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    container_name: fams-admin
    command: npm run dev
    env_file:
      - ./admin/.env
    ports:
      - "8000:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: fams-server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: fams-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - famsgres:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  famsgres:
    name: famsgres

networks:
  app-network:
    name: fams-net
    driver: bridge
