import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { poppins } from "@/src/styles/font";
import AuthProvider from "@/src/components/AuthProvider";

export const metadata: Metadata = {
  title: "FAMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Providers>
          <AuthProvider>
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
