import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { poppins } from "@/styles/font";

export const metadata: Metadata = {
  title: "FAMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
