import type { Metadata } from "next";
<<<<<<< HEAD
import { Toaster } from 'sonner';
=======
>>>>>>> origin/main
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "FAMS - Faculty Appointment System",
  description: "Faculty Appointment System",
>>>>>>> origin/main
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
        <Toaster position="top-right" richColors />
=======
      <body className={`antialiased bg-gray-50/50`}>
        <Providers>{children}</Providers>
>>>>>>> origin/main
      </body>
    </html>
  );
}
