FROM python:3.11-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y poppler-utils && apt-get clean

COPY requirements.txt .

RUN pip install --default-timeout=100 -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
